Repository terraform-providers/terraform-provider-heroku, pull requests merged in 2018-06, with the labels that each got.

#60 Update heroku-go and fix related compile errors
  heroku/resource_heroku_addon.go
  heroku/resource_heroku_space.go
  heroku/resource_heroku_team_collaborator.go
  vendor/github.com/cyberdelia/heroku-go/v3/heroku.go
  vendor/github.com/cyberdelia/heroku-go/v3/schema.json
  vendor/vendor.json
Labels: dependencies, easy

#57 Add heroku_space_peering_info data resource
  CHANGELOG.md
  heroku/data_source_heroku_space.go
  heroku/data_source_heroku_space_peering_info.go
  heroku/data_source_heroku_space_peering_info_test.go
  heroku/provider.go
  website/docs/d/space.html.markdown
  website/docs/d/space_peering_info.html.markdown
  website/heroku.erb
Labels: enhancement, new-data-source

#64 Fix Attachment Ids
  heroku/resource_heroku_addon_attachment.go
  heroku/resource_heroku_addon_attachment_test.go
Labels: bug

#58 Add a heroku_space_peering_request_accepter resource for acceping peering requests into Private Spaces
  heroku/provider.go
  heroku/resource_heroku_space_peering_connection_accepter.go
  website/docs/r/space_peering_connection_accepter.html.markdown
  website/heroku.erb
Labels: enhancement, new-resource

#63 Add space attributes for outbound IPs and shield
  README.md
  heroku/data_source_heroku_space.go
  heroku/resource_heroku_space.go
  heroku/resource_heroku_space_test.go
  website/docs/d/space.html.markdown
  website/docs/r/space.html.markdown
Labels: enhancement
