Repository terraform-providers/terraform-provider-heroku, pull requests merged in 2018-11, with the labels that each got.

#137 Investigate & Fix the Following Test Failures
  heroku/resource_heroku_domain_test.go
Labels: size/XS

#139 Fetch slug archives via HTTPS
  heroku/import_heroku_slug_test.go
  heroku/resource_heroku_slug.go
  heroku/resource_heroku_slug_test.go
  website/docs/r/slug.html.markdown
Labels: size/L

#143 Typos in Documentation
  heroku/import_heroku_app_feature_test.go
  heroku/resource_heroku_app_feature.go
  website/docs/r/account_feature.html.markdown
  website/docs/r/app_feature.html.markdown
Labels: size/S

#135 Retry with backoff when rate-limited
  Gopkg.lock
  README.md
  heroku/config.go
  vendor/github.com/cenkalti/backoff/.gitignore
  vendor/github.com/cenkalti/backoff/.travis.yml
  vendor/github.com/cenkalti/backoff/LICENSE
  vendor/github.com/cenkalti/backoff/README.md
  vendor/github.com/cenkalti/backoff/backoff.go
  vendor/github.com/cenkalti/backoff/context.go
  vendor/github.com/cenkalti/backoff/exponential.go
  vendor/github.com/cenkalti/backoff/retry.go
  vendor/github.com/cenkalti/backoff/ticker.go
  vendor/github.com/cenkalti/backoff/tries.go
  vendor/github.com/heroku/heroku-go/v3/round_trip_with_retry_backoff.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/ulikunitz/xz/cmd/gxz/licenses.go
  vendor/github.com/ulikunitz/xz/cmd/xb/copyright.go
Labels: size/XXL

#144 Undo test API URL
  heroku/config.go
Labels: regression, size/XS

#147 fix bad formatting in docs
  website/docs/index.html.markdown
  website/docs/r/cert.html.markdown
  website/docs/r/domain.html.markdown
  website/docs/r/drain.html.markdown
  website/docs/r/formation.html.markdown
  website/docs/r/slug.html.markdown
  website/docs/r/space_app_access.markdown
Labels: size/M

#148 fix panic condition in parseCompositeID
  heroku/provider.go
  heroku/resource_heroku_account_feature.go
  heroku/resource_heroku_account_feature_test.go
  heroku/resource_heroku_app_feature.go
  heroku/resource_heroku_app_feature_test.go
  heroku/resource_heroku_cert.go
  heroku/resource_heroku_domain.go
  heroku/resource_heroku_drain.go
  heroku/resource_heroku_formation.go
  heroku/resource_heroku_slug.go
  heroku/resource_heroku_space_app_access.go
  heroku/resource_heroku_space_vpn_connection.go
  heroku/resource_heroku_space_vpn_connection_test.go
  heroku/resource_heroku_team_collaborator.go
  heroku/resource_heroku_team_member.go
  heroku/resource_heroku_team_member_test.go
Labels: size/M
