Repository terraform-providers/terraform-provider-heroku, pull requests merged in 2018-12, with the labels that each got.

#149 Build resource
  Gopkg.lock
  Gopkg.toml
  README.md
  heroku/import_heroku_build_test.go
  heroku/provider.go
  heroku/resource_heroku_build.go
  heroku/resource_heroku_build_test.go
  heroku/resource_heroku_slug.go
  heroku/test-fixtures/app-2.tgz
  heroku/test-fixtures/app-2/Gemfile
  heroku/test-fixtures/app-2/Gemfile.lock
  heroku/test-fixtures/app-2/README.md
  heroku/test-fixtures/app-2/server.rb
  heroku/test-fixtures/app.tgz
  heroku/test-fixtures/app/Gemfile
  heroku/test-fixtures/app/Gemfile.lock
  vendor/github.com/verybluebot/tarinator-go/.gitignore
  vendor/github.com/verybluebot/tarinator-go/LICENCE.md
  vendor/github.com/verybluebot/tarinator-go/README.md
  vendor/github.com/verybluebot/tarinator-go/somescript.sh
  vendor/github.com/verybluebot/tarinator-go/tarinator.go
  website/docs/r/build.html.markdown
Labels: dependencies, documentation, size/XXL

#151 Allow setting URL
  heroku/config.go
  heroku/provider.go
Labels: size/XS

#152 Prep Changelog for 1.7.0 release
  CHANGELOG.md
Labels: size/XS

#154 Fix Build resource tests with updated local source checksums
  heroku/resource_heroku_build_test.go
Labels: size/XS

#142 Add provider configuration for backend
  heroku/config.go
  heroku/helper.go
  heroku/provider.go
  heroku/resource_heroku_app.go
  heroku/resource_heroku_domain.go
  heroku/resource_heroku_space.go
  website/docs/index.html.markdown
Labels: documentation, size/XL

#155 Really fix Build resource tests
  heroku/resource_heroku_build_test.go
Labels: size/S

#157 add missing features/fixes to changelog
  CHANGELOG.md
Labels: size/XS

#156 📚 Build resource doc fixups
  website/docs/r/build.html.markdown
  website/heroku.erb
Labels: documentation, size/XS

#162 make provider version available at runtime
  GNUmakefile
  heroku/helper.go
  version/version.go
Labels: size/XS
