Repository terraform-providers/terraform-provider-heroku, pull requests merged in 2018-10, with the labels that each got.

#127 Export the UUID of the Heroku app.
  heroku/resource_heroku_app.go
  heroku/resource_heroku_app_test.go
  website/docs/r/app.html.markdown
Labels: size/XS

#128 Update CHANGELOG missed in #127.
  CHANGELOG.md
Labels: size/XS

#131 Fix Integration Tests
  CHANGELOG.md
  heroku/resource_heroku_app_test.go
  heroku/resource_heroku_slug_test.go
  heroku/resource_heroku_team_member_test.go
Labels: bug, crash, size/XS

#132 Update changelog to 1.5.0
  CHANGELOG.md
Labels: size/XS

#130 Data source heroku addon
  heroku/data_source_heroku_addon.go
  heroku/data_source_heroku_addon_test.go
  heroku/provider.go
  website/docs/d/addon.html.markdown
  website/heroku.erb
Labels: size/L

#136 Fix formation.html.markdown
  website/docs/r/formation.html.markdown
Labels: size/XS
