Repository terraform-providers/terraform-provider-heroku, pull requests merged in 2019-03, with the labels that each got.

#187 📚 clarify usage of Heroku Teams
  website/docs/r/app.html.markdown
  website/docs/r/space.html.markdown
  website/docs/r/team_collaborator.html.markdown
  website/docs/r/team_member.html.markdown
Labels: documentation, size/S

#188 New data resource: Heroku Team
  helper/test/config.go
  heroku/data_source_heroku_team.go
  heroku/data_source_heroku_team_test.go
  heroku/provider.go
  website/docs/d/team.html.markdown
  website/heroku.erb
Labels: documentation, size/L

#191 Fix tests using SSL Endpoint DNS target
  heroku/resource_heroku_cert_test.go
Labels: size/XS

#183 New Resource: Heroku Config & Heroku App Config Association
  CHANGELOG.md
  heroku/helper.go
  heroku/import_heroku_config_association_test.go
  heroku/import_heroku_config_test.go
  heroku/provider.go
  heroku/resource_heroku_app.go
  heroku/resource_heroku_app_config_association.go
  heroku/resource_heroku_app_config_association_test.go
  heroku/resource_heroku_config.go
  heroku/resource_heroku_config_test.go
  heroku/resource_heroku_formation.go
  website/docs/r/app.html.markdown
  website/docs/r/app_config_association.html.markdown
  website/docs/r/config.html.markdown
  website/heroku.erb
Labels: documentation, size/XL
