Repository terraform-providers/terraform-provider-heroku, pull requests merged in 2019-08, with the labels that each got.

#229 Fixing segfault when app with AppName does not exist
  heroku/resource_heroku_formation.go
Labels: size/XS

#230 Fix Error: strconv.Atoi: parsing "": invalid syntax
  heroku/resource_heroku_addon_migrate.go
Labels: size/M

#232 Stop creating cedar-14 apps during tests
  heroku/resource_heroku_app_test.go
Labels: size/XS

#228 Swap out satori/uuid for google/uuid
  go.mod
  go.sum
  heroku/resource_heroku_slug.go
  heroku/validators.go
  heroku/validators_test.go
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/satori/uuid/.travis.yml
  vendor/github.com/satori/uuid/LICENSE
  vendor/github.com/satori/uuid/README.md
  vendor/github.com/satori/uuid/codec.go
  vendor/github.com/satori/uuid/generator.go
  vendor/github.com/satori/uuid/sql.go
  vendor/github.com/satori/uuid/uuid.go
  vendor/github.com/verybluebot/tarinator-go/LICENSE.md
  vendor/modules.txt
Labels: dependencies, size/XL
