Repository terraform-providers/terraform-provider-heroku, pull requests merged in 2019-02, with the labels that each got.

#167 Add support for Heroku Private Space CIDR and Data CIDR
  heroku/data_source_heroku_space.go
  heroku/resource_heroku_space.go
  heroku/resource_heroku_space_test.go
  website/docs/d/space.html.markdown
  website/docs/r/space.html.markdown
Labels: dependencies, documentation, size/M

#174 Fix tests in CI
  heroku/import_heroku_team_collaborator_test.go
  heroku/resource_heroku_app_test.go
  heroku/resource_heroku_slug_test.go
  heroku/resource_heroku_team_collaborator_test.go
Labels: size/XS

#175 Doc improvements
  README.md
  website/docs/index.html.markdown
  website/docs/r/account_feature.html.markdown
  website/docs/r/app_feature.html.markdown
  website/docs/r/space_app_access.markdown
Labels: documentation, size/M

#181 Make source tarball in a temporary location
  heroku/resource_heroku_build.go
  heroku/resource_heroku_build_test.go
Labels: size/S
