Repository terraform-providers/terraform-provider-heroku, pull requests merged in 2019-07, with the labels that each got.

#212 Change config from block to attribute assignment
  website/docs/r/addon.html.markdown
Labels: documentation, size/XS

#215 Fix documentation example for import of heroku_app_feature
  website/docs/r/app_feature.html.markdown
Labels: documentation, size/XS

#216 Fix heroku_domain description
  website/docs/r/domain.html.markdown
Labels: documentation, size/XS

#217 Fix: Upgrade to v2 requires recreation of add-ons
  CHANGELOG.md
  heroku/resource_heroku_addon.go
  heroku/resource_heroku_addon_migrate.go
Labels: size/M

#221 Grammar fix
  website/docs/r/app_config_association.html.markdown
Labels: documentation, size/XS

#210 Ability to set addon name
  heroku/resource_heroku_addon.go
  heroku/resource_heroku_addon_test.go
  website/docs/r/addon.html.markdown
Labels: documentation, size/L

#225 Fix misnamed resource reference in documentation
  website/docs/r/config.html.markdown
Labels: documentation, size/XS

#224 Clarify `heroku_build` `source` docs
  website/docs/r/build.html.markdown
Labels: documentation, size/XS
