Repository terraform-providers/terraform-provider-heroku, pull requests merged in 2019-01, with the labels that each got.

#161 Identify Terraform API requests via user-agent header
  GNUmakefile
  heroku/config.go
Labels: size/XS

#164 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
Labels: size/XS

#163 New Heroku App attribute: sensitive_config_vars
  heroku/resource_heroku_app.go
  heroku/resource_heroku_app_test.go
  website/docs/r/app.html.markdown
Labels: documentation, size/XL

#166 Update Changelog for 1.7.3
  CHANGELOG.md
Labels: size/XS

#169 upgrade heroku-go
  Gopkg.lock
  heroku/resource_heroku_build.go
  vendor/github.com/heroku/heroku-go/v3/heroku.go
  vendor/github.com/heroku/heroku-go/v3/schema.json
Labels: dependencies, size/XXL

#171 📚 clarify test parameters
  TESTING.md
Labels: size/XS
