Repository terraform-providers/terraform-provider-heroku, pull requests merged in 2020-03, with the labels that each got.

#245 Remove quoted interpolation-only expressions
  website/docs/index.html.markdown
Labels: documentation, size/XS

#256 Support heroku pipeline config_vars
  .travis.yml
  go.mod
  go.sum
  heroku/import_heroku_pipeline_config_var_test.go
  heroku/import_heroku_pipeline_test.go
  heroku/provider.go
  heroku/resource_heroku_app.go
  heroku/resource_heroku_app_config_association.go
  heroku/resource_heroku_cert.go
  heroku/resource_heroku_config.go
  heroku/resource_heroku_pipeline_config_var.go
  heroku/resource_heroku_pipeline_config_var_test.go
  heroku/resource_heroku_pipeline_test.go
  vendor/github.com/heroku/heroku-go/v5/heroku.go
  vendor/github.com/heroku/heroku-go/v5/schema.json
  vendor/modules.txt
  website/docs/r/app_config_association.html.markdown
  website/docs/r/pipeline_config_var.html.markdown
  website/docs/r/pipeline_coupling.html.markdown
  website/docs/r/space_inbound_ruleset.html.markdown
  website/docs/r/space_peering_connection_accepter.html.markdown
  website/docs/r/space_vpn_connection.html.markdown
  website/heroku.erb
Labels: dependencies, documentation, size/XXL

#258 Prep v2.3.0 release
  CHANGELOG.md
Labels: size/XS
