Repository terraform-providers/terraform-provider-heroku, pull requests merged in 2020-04, with the labels that each got.

#255 Fixes in the datasource for heroku app
  heroku/data_source_heroku_app.go
  heroku/data_source_heroku_app_test.go
  website/docs/d/app.html.markdown
Labels: documentation, size/S

#260 GitHub Actions for acceptance tests & release binaries
  .github/workflows/acceptance-tests.yml
  .github/workflows/publish-binaries-on-release.yml
  GNUmakefile
Labels: size/M

#261 Fix random VPN create failures
  GNUmakefile
  heroku/resource_heroku_space_vpn_connection.go
Labels: size/S

#257 Various bug fixes for `heroku_app` resource
  heroku/data_source_heroku_app.go
  heroku/import_heroku_app_test.go
  heroku/resource_heroku_app.go
  heroku/resource_heroku_app_test.go
  heroku/resource_heroku_formation_test.go
  website/docs/r/app.html.markdown
Labels: documentation, size/XL

#259 Support Pipeline Ownership
  .github/workflows/acceptance-tests.yml
  TESTING.md
  helper/test/config.go
  heroku/import_heroku_pipeline_test.go
  heroku/resource_heroku_pipeline.go
  heroku/resource_heroku_pipeline_test.go
  website/docs/r/pipeline.html.markdown
Labels: documentation, size/L

#263 [doc] Remove `name` from heroku_config example
  website/docs/r/app_config_association.html.markdown
Labels: documentation, size/XS
