Repository terraform-providers/terraform-provider-heroku, pull requests merged in 2020-06, with the labels that each got.

#270 Clarify usage constraints of Build source path
  website/docs/r/build.html.markdown
Labels: documentation, size/XS

#271 Upgrade acceptance tests to Go 1.14
  .github/workflows/acceptance-tests.yml
  README.md
Labels: size/XS

#268 There should be a data source for `heroku_pipeline`
  heroku/data_source_heroku_pipeline.go
  heroku/data_source_heroku_pipeline_test.go
  heroku/provider.go
  website/docs/d/pipeline.html.markdown
  website/heroku.erb
Labels: documentation, size/M
